name: shyro_theme
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/ShyroTeam/shyro_theme

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.5
  flutter_gen_runner: ^4.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/montserrat-regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/montserrat-medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/montserrat-semibold.ttf
          weight: 600
